name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install shellcheck
      run: |
        wget -qO- https://github.com/koalaman/shellcheck/releases/download/v0.7.1/shellcheck-v0.7.1.linux.x86_64.tar.xz | tar -xJf -
        cd shellcheck-v0.7.1/
        sudo cp shellcheck /usr/local/bin

    - name: lint with shellcheck
      run: shellcheck clean.sh pipeline.sh run.sh split.sh transform.sh
